/* DROP DATABASE IF EXISTS `steam`; */
CREATE DATABASE IF NOT EXISTS `steam`;
USE `steam`;

CREATE TABLE DOCUMENT (
  ID 				VARCHAR(40) 	NOT NULL,
  CONTENT			TEXT,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN_ID FOREIGN KEY (ID) REFERENCES piston.TILE (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO DOCUMENT (ID, CONTENT) VALUES 
	('9da68328-8b01-42d9-8c53-2d8b76656f8e', '# App Administration'),
	('4c3a0850-e69d-4c13-ad44-849aa3625472', '# Site Administration');